### ISSUE TITLE
Banner not defined

### ISSUE THREAD

**Issue by meunierf** [hacker900123/XSS-Freak#1]
python3 XSS-Freak.py command results: 

> Traceback (most recent call last):
>   File "XSS-Freak.py", line 16, in <module>
>     print(Fore.BLUE + Style.BRIGHT + str(Banner("XSS FREAK")))
> NameError: name 'Banner' is not defined

Python 3.7.3rc1
Kali 2019.1a

**Comment by Anonymous1807** [comment]
@meunierf It looks like I have encountered the same issue, luckily I could solve it.
Just go to the directory where you installed the XSS-Freak and open **XSS-Freak.py** 
**` $ cd directory && gedit XSS-Freak.py`**
After that change **line 16** to 
**`print(Fore.BLUE + Style.BRIGHT + str("XSS FREAK"))`**
And that's all, save the file and everything will be working!

**Comment by hacker900123** [comment]
okay. just go to the terminal and write: pip3 install asciistuff
it should fix your problem and if it didnt work, feel free to re contact me.

**Comment by meunierf** [comment]
> XSS FREAK
> >> [+] Give Me A Target To Destroy
> >> [?] Enter Target: http://www.gcvinfo.com
> >> [*] Enter File Containing XSS Payloads to Try: xsspayload.txt
> >> [*] Searching Target For Possible Links And Directories
> Traceback (most recent call last):
>   File "XSS-Freak.py", line 97, in <module>
>     find_directories()
>   File "XSS-Freak.py", line 46, in find_directories
>     user_agent = generate_user_agent()
> NameError: name 'generate_user_agent' is not defined
> 

root@kali:/opt/XSS-Freak#

**Comment by meunierf** [comment]
> okay. just go to the terminal and write: pip3 install asciistuff
> it should fix your problem and if it didnt work, feel free to re contact me.

It doesn't. I had to remove the print Banner parameter.

**Comment by hacker900123** [comment]
okay that is one way to fix it.

**Comment by santiago0072002** [comment]
Traceback (most recent call last):
  File "XSS-Freak.py", line 16, in <module>
    print(Fore.BLUE + Style.BRIGHT + str(Banner("XSS FREAK")))
NameError: name 'Banner' is not defined
